### ISSUE TITLE
The Link in the SPHINX readme leads to a file that no longer exists

### ISSUE THREAD

**Issue by StrangeTcy** [Alpha-VLLM/LLaMA2-Accessory#100]
Perhaps a link to an Arxiv page would be preferable?

**Comment by gaopengpjlab** [comment]
Official arxiv will be released soon.

**Comment by gaopengpjlab** [comment]
Please try the following link:
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/SPHINX/SPHINX_paper.pdf

**Comment by StrangeTcy** [comment]
Amazing, thanks
