### ISSUE TITLE
Number of parameters Sphinx

### ISSUE THREAD

**Issue by ThierryDeruyttere** [Alpha-VLLM/LLaMA2-Accessory#106]
Hi,

Thanks for the awesome Sphinx model!
I was just wondering how many parameters this model has.
I can't seem to find this in the report.

**Comment by linziyi96** [comment]
SPHINX contains about 16.5B parameters, among which around 13B are in the language model and are trained, around 3.5B are in the visual encoders and are frozen (1B in QFormer, 0.85B in OpenCLIP ConvNext-xxl, 1B in DINOv2 ViT-g/14, 0.4B in CLIP ViT-L).
