### ISSUE TITLE
tokenizer.model not found

### ISSUE THREAD

**Issue by axin1301** [Alpha-VLLM/LLaMA2-Accessory#107]
Hi, thank you for your amazing work. I am new to the LLaMA, and I tried to run inference.py in SPHINX. However, I cannot find the tokenizer.model  in your repository. Could you please provide any information where I can find it? Thank you.

**Comment by gaopengpjlab** [comment]
tokenizer.model is provided by the original llama download package. Please download it using the methods provided by llama  repo.
