### ISSUE TITLE
OutOfMemoryError when running Sphinx with 2 A30 GPUs

### ISSUE THREAD

**Issue by codonna9** [Alpha-VLLM/LLaMA2-Accessory#110]
Hello, 
Thank you so much for releasing the models, paper and code. I tried Sphinx's demo and I'm very impressed with the demo results. However,  when I tried running the file "inference.py" with 2 A30 GPU (each has 24 GB RAM) and MODEL_PARALLEL_SIZE = 2, I got torch.cuda.OutOfMemoryError.

Are there any other ways I can run Sphinx models with 2 A30 GPU?

**Comment by xulinui** [comment]
<img width="176" alt="截屏2023-11-20 15 15 02" src="https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/66818560/30302941-6bdb-4136-b41e-44c9d1637e8c">

**Comment by quizD** [comment]
Did you solve this question？

**Comment by codonna9** [comment]
No, I haven't been able to solve this. I guess, we'll have to wait for the team to release some model parallel inference code but it's probably not easy to do

**Comment by ChrisLiu6** [comment]
Hi, please consider using quantization. See the following for example:

https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/accessory/demos/multi_turn_mm_box.py#L77

We have not tried with 24G-memory GPUs, but as a rough estimation, the GPU memory cost for hosting SPHINX on two GPUs should be close to 24G (without quantization). So you may be able to successfully run it without quantization after some optimization, but overall it is really extreme.

**Comment by gaopengpjlab** [comment]
@quizD @codonna9 Please refer to issue 114.
https://github.com/Alpha-VLLM/LLaMA2-Accessory/issues/114

**Comment by codonna9** [comment]
> Hi, please consider using quantization. See the following for example: https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/accessory/demos/multi_turn_mm_box.py#L77
> 
> _If you don't wanna quantize the model:_ We have not tried with 24G-memory GPUs, but as a rough estimation, the GPU memory cost for hosting SPHINX on two GPUs should be close to 24G (without quantization). So you may be able to successfully run it without quantization after some optimization, but overall it is really extreme.

Thanks a lot for the quantization suggestion. I'll try that and I'll probably explore ways to dispatch the model weights to multiple GPUs like what they do here:
https://huggingface.co/THUDM/cogvlm-chat-hf

**Comment by codonna9** [comment]
> @quizD @codonna9 Please refer to issue 114. #114

Thanks a lot! I'll follow that issue
