### ISSUE TITLE
Do you use only first conversation in the data?

### ISSUE THREAD

**Issue by yeonju7kim** [Alpha-VLLM/LLaMA2-Accessory#117]
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/32f9a9ebbaccfa5a1cda95bc3172f6129a8680f7/accessory/data/alpaca.py#L223C1-L224C65

In this code, it looks like the model only uses the first conversation.
I found the same thing in LLaMA-adapter repository.

https://github.com/OpenGVLab/LLaMA-Adapter/issues/123

Is there any reason why the model only uses the first conversation?

**Comment by gaopengpjlab** [comment]
SPHINX use multi-turn conversation.

**Comment by linziyi96** [comment]
We use this dataset for fine-tuning: https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/32f9a9ebbaccfa5a1cda95bc3172f6129a8680f7/accessory/data/conversation/dataset.py
