### ISSUE TITLE
Limited models for fine-tuning

### ISSUE THREAD

**Issue by kb-open** [Alpha-VLLM/LLaMA2-Accessory#12]
Support for models for fine-tuning seems to be very limited.
Is LLaMA-2 fine-tuning supported?
Will MPT / Falcon fine-tuning be supported?

**Comment by gaopengpjlab** [comment]
This repo is mainly designed for finetuning LLaMa2 upon various datasets. What do you mean by "Is LLaMA-2 fine-tuning supported?" ?
Currently, we mainly support LLaMa2 finetuning.
