### ISSUE TITLE
Where are the codes of visual embeddings mixing of SPHINX?

### ISSUE THREAD

**Issue by Arsiuuu** [Alpha-VLLM/LLaMA2-Accessory#120]
Thanks~

**Comment by linziyi96** [comment]
Please see the following method

https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/e703eee103b6571e43b48e39de8f7b7e5e1ca3ad/accessory/model/LLM/llama_ens5.py#L376-L457
