### ISSUE TITLE
How to evaluate SPHINX on refCOCO?

### ISSUE THREAD

**Issue by CrazyLenmon** [Alpha-VLLM/LLaMA2-Accessory#130]
Thanks for your great work! I'm wondering how to evaluate your model on refCOCO. I see that some documents and codes you didn't release including the utils and scripts in accessory/eval_mm/. When do you plan to release? And is it possible for me to evaluate only on one dataset?  I am looking forward to your reply.
![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/57952684/8ddd6584-09bc-47d4-b665-e60fa5418f34)

**Comment by CrazyLenmon** [comment]
> Sorry for the mistakes. The missing files are updated in #131. We update the instruction for evaluation on one dataset in _README.md_.

There are still some funcitons missing. It doesn't work. Could you please check it again? 
![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/57952684/a5fad230-d547-44c6-a3cc-f07553c11c61)

**Comment by Artanic30** [comment]
The missing file is updated in https://github.com/Alpha-VLLM/LLaMA2-Accessory/pull/133.

**Comment by CrazyLenmon** [comment]
> The missing file is updated in #133.

Thank you. And I noticed that there are some mistakes in codes. I suggest that you may check the codes. Some mistakes such as "pretrined_path" and like in this image. You may try to run the version you commited to find these codes mistakes. Anyway, thank you for your great effort.
![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/57952684/f0b6aad4-6394-4f3b-a55a-73506cdbe5e0)

**Comment by Artanic30** [comment]
Thanks for pointing out the code version issue, we will fix the code as soon as possible.
