### ISSUE TITLE
Running SPHINX without SLRUM

### ISSUE THREAD

**Issue by babla9** [Alpha-VLLM/LLaMA2-Accessory#161]
Hi, I'm trying to run this [finetuning SPHINX script](https://github.com/Alpha-VLLM/LLaMA2-Accessory/tree/main/SPHINX#finetuning) on a 8xV100 machine. 

However, my machine doesnt have SLURM installed, so how do I allow the script to access all gpus on the cluster without using srun / slurm? 

Thanks!

**Comment by ChrisLiu6** [comment]
replace `srun python xxx` with `torchrun --nproc_per_node=8 xxx` should be all you need
