### ISSUE TITLE
The performance of SPHINX Mixtral MoE

### ISSUE THREAD

**Issue by zhongshsh** [Alpha-VLLM/LLaMA2-Accessory#168]
What is the performance of **SPHINX Mixtral MoE** in some general VQA benchmarks as shown in https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/SPHINX/SPHINX_paper.pdf ?
![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/62104945/58e14c29-aba0-48f7-9a05-b79af098b62f)

**Comment by gaopengpjlab** [comment]
Please refer to SPHINX-MoE paper.

https://arxiv.org/pdf/2402.05935.pdf
