### ISSUE TITLE
Reference Inference Code

### ISSUE THREAD

**Issue by rsomani95** [Alpha-VLLM/LLaMA2-Accessory#17]
Hi, thank you for sharing your work. 

I'm excited to try these models out but don't see any inference code. The README only points to pretraining / finetuning scripts. Should I be looking at the [LLaMA-Adapter](https://github.com/OpenGVLab/LLaMA-Adapter) codebase for this?

Thanks.

**Comment by Enderfga** [comment]
Thank you for your interest in our models. You can find all the required inference scripts for single-turn, multi-turn, and multi-modal dialogues under the `accessory/demos` directory. The usage across these different dialogues remains similar.

Here's a command example to launch a single-turn demo:

```bash
torchrun --nproc-per-node=1 demos/single_turn.py \
--llama_config /path/to/params.json --tokenizer_path /path/to/tokenizer.model \
--pretrained_path /path/to/alpaca_finetuned
```

Should you encounter any issues or have further questions, please do not hesitate to reach out. Wishing you a smooth experience with our models!

**Comment by ChrisLiu6** [comment]
For each example in [finetune.md](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/finetune.md), we provide a **Host Local Demo** command. Running the command will host a local gradio demo on your machine where you can test your model. You may either use you own trained checkpoint, or that we provide at **Model Release** to host the demo.
