### ISSUE TITLE
Clarification of SEED score

### ISSUE THREAD

**Issue by Isaachhh** [Alpha-VLLM/LLaMA2-Accessory#194]
<img width="453" alt="Screenshot 2024-04-30 at 14 19 23" src="https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/93458689/68917535-70e7-4e51-8f0d-b3ccc840829b">

I notice that SPHINX achieve 70+ on SEED-Bench. I wonder whether you report image accuracy other than total accuracy, because LLaVA reports total accuracy (58.6 for 7B and 61.6 for 13B).

**Comment by Artanic30** [comment]
Thanks for pointing out, it's a mistake in our paper. We will correct the results of LLaVA in latest version.
