### ISSUE TITLE
About the model scale used for singel-modal and multi-model data.

### ISSUE THREAD

**Issue by junwenxiong** [Alpha-VLLM/LLaMA2-Accessory#20]
Why 7B llama2 model is used to fine-tune the single-modal data, while 13B model is used for the multi-modal data, and what is the reason that the 7B model cannot be use both types of data? Thank you!

**Comment by gaopengpjlab** [comment]
Models with various size are going to be released. Stay tuned.

**Comment by junwenxiong** [comment]
This mean that there is also a multimodal model of 7B llama2?

**Comment by ChrisLiu6** [comment]
> This mean that there is also a multimodal model of 7B llama2?

You can definitely tune a multi-modal model based on llama2 7B. You can even tune a 70B multi-modal model if you want. There is no binding relationship between model size and model purpose. We release different-sized models majorly to demonstrate how LLaMA2-Accessory supports different model sizes.
