### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [Alpha-VLLM/LLaMA2-Accessory#202]
Thank you for your amazing open source project！

I have a batch of image and text pairs, and I would like to use your Large-DiT-T2I to train a Text-to-Image DiT model. Once I have installed the necessary packages, I will download consolidated_ema.00-of-01.pth and model.args.pth to the pretrained model folder, and then use the following command to start:

python -u demo.py --ckpt pretrained_model

Then I received the following error message:

![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/36565076/0644f2ad-6676-45fa-9a20-001fdc8d26e9)
![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/36565076/c724e9ee-2bd8-44b9-8f06-442bfa91f0a5)

May I ask how to solve this problem? I hope to receive your reply

**Comment by gaopengpjlab** [comment]
Please use our latest Lumina-series model.

https://github.com/Alpha-VLLM/Lumina-T2X

**Comment by zcdliuwei** [comment]
> Please use our latest Lumina-series model.
> 
> https://github.com/Alpha-VLLM/Lumina-T2X

Thanks for your kindly reply
I will give it a try soon
