### ISSUE TITLE
Hardware requirement for continuing the pretraining

### ISSUE THREAD

**Issue by Kefan-pauline** [Alpha-VLLM/LLaMA2-Accessory#21]
What is the minimal hardware requirement (in VRAM) for continuing the pretraining with new text corpus for LLaMa2 7B with fp32/fp16 precision? Let's say that input length will be limited to 2048 tokens and batch size = 1.

**Comment by Seagull619** [comment]
FYI, I used fp16, batch size=1, max_words=2048. When training with two GPUs, I need 48GB of GPU memory.
