### ISSUE TITLE
模型输出无意义的内容

### ISSUE THREAD

**Issue by altqxd** [Alpha-VLLM/LLaMA2-Accessory#22]
从huggingface现在alpaca的模型之后
按照torchrun --nproc-per-node=1  demos/single_turn.py --llama_config /root/autodl-tmp/model/LLaMA2-Accessory/config/7B_params.json --tokenizer_path /root/autodl-tmp/model/LLaMA2-Accessory/config/tokenizer.model --pretrained_path /root/autodl-tmp/model/LLaMA2-Accessory/finetune/sg/alpaca
官网提供的命令运行，可以正常启动gradio，但是模型输出的是无意义的内容

![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/119843642/01e9291e-2586-43db-8d56-748d9a5f84a4)

**Comment by ChrisLiu6** [comment]
Hi, note that we release delta patches of our trained checkpoints instead of off-the-shelf checkpoints to comply with llama's license. Please follow the instructions [here](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/inference.md) to merge the weights before inference.

**Comment by altqxd** [comment]
> 

thanks,i will try

**Comment by altqxd** [comment]
> Hi, note that we release delta patches of our trained checkpoints instead of off-the-shelf checkpoints to comply with llama's license. Please follow the instructions [here](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/inference.md) to merge the weights before inference.

thanks,i will try
