### ISSUE TITLE
how to transform the weight into consolidated version?

### ISSUE THREAD

**Issue by ZhenYangIACAS** [Alpha-VLLM/LLaMA2-Accessory#23]
As your code in load_pretrained,  'meta-ori' format does not support multi-gpu? Therefore, how can I transform the weight into consolidated format?

**Comment by ChrisLiu6** [comment]
抱歉，但可能存在一些误解。加载"meta-ori"类型的预训练模型是支持多GPU的。您是否将"Loading from checkpoints of different mp_world_size is currently not supported."误以为不支持多GPU？ 这句话是说meta提供的checkpoint的model parallel size是多少，我们实验的model parallel size也得设成一样，比如13B meta给的checkpiont的model parallel size是2，我们也需要将model parallel size设成2。

**Comment by ZhenYangIACAS** [comment]
@ChrisLiu6  但是代码里读的是mp_world_size。 而且还 assert ckpt_mp_world_size == mp_world_size. 对于7B 模型， mp_world_size 只能是1了

**Comment by ZhenYangIACAS** [comment]
@ChrisLiu6 看到前面有设置model_parallel, 请问一下，这里为啥不能直接设置model_parallel 为dist.get_world_size?

**Comment by ChrisLiu6** [comment]
> @ChrisLiu6 但是代码里读的是mp_world_size。 而且还 assert ckpt_mp_world_size == mp_world_size. 对于7B 模型， mp_world_size 只能是1了

model parallel size和world size是不一样的。world size = model parallel size * data parallel size。假设有八张GPU，完全可以将model parallel size设为1，对应data parallel size为8。model parallel size决定的是llama中的parallellinear层要被拆分成多少份（每个model parallel rank占一份），而对于具有相同model parallel rank的进程来说，其参数、梯度和优化器状态会进一步通过FSDP在data parallel group内被拆分

**Comment by ZhenYangIACAS** [comment]
@ChrisLiu6 感谢耐心解答。借楼问一个问题，你们到底用的torch, cuda 版本是多少？我按照requirement 配置的环境，发现经常有各种torch api 对不上，或者就是报 no cuad image kernel. 这边按照自己的版本用了1.x pytorch；但是1. x pytorch 的FSDP 不支持ignore_parameters, 导致也是跑不起来。

**Comment by Seagull619** [comment]
> @ChrisLiu6 感谢耐心解答。借楼问一个问题，你们到底用的torch, cuda 版本是多少？我按照requirement 配置的环境，发现经常有各种torch api 对不上，或者就是报 no cuad image kernel. 这边按照自己的版本用了1.x pytorch；但是1. x pytorch 的FSDP 不支持ignore_parameters, 导致也是跑不起来。

I am using torch: 2.0.1, cuda: 11.7. Everything is working fine.

**Comment by ChrisLiu6** [comment]
> @ChrisLiu6 感谢耐心解答。借楼问一个问题，你们到底用的torch, cuda 版本是多少？我按照requirement 配置的环境，发现经常有各种torch api 对不上，或者就是报 no cuad image kernel. 这边按照自己的版本用了1.x pytorch；但是1. x pytorch 的FSDP 不支持ignore_parameters, 导致也是跑不起来。

torch的FSDP处于频繁更新的状态，不同版本的api会有变化，因此torch版本务必和我们保持一致（2.0.1）。另外要注意下apex要求本地cuda版本与torch的cuda版本一致，否则编译会失败。我们的cuda版本统一是11.7。

**Comment by ZhenYangIACAS** [comment]
@Seagull619   what is your cuda driver version?

**Comment by Seagull619** [comment]
> @Seagull619 what is your cuda driver version?

535.54.03
