### ISSUE TITLE
which model provides the ability of text output with object detection result?

### ISSUE THREAD

**Issue by Kanon777** [Alpha-VLLM/LLaMA2-Accessory#24]
i found the demo images on the front page shows that the llama-accessory has the ability of generating text output with object detection result, so can you suggest which model provide this ability or can you provide some more demo for it? thanks

**Comment by Artanic30** [comment]
Thank you for your interest in our work. The llama-accessory's capability to generate text output along with object detection results is achieved through training with [Shikra](https://github.com/shikras/shikra) dataset. We are currently in the process of organizing the code and data for this specific version. Rest assured, we are actively working on its preparation and plan to release it in the near future. Your patience is greatly appreciated as we finalize these details.
