### ISSUE TITLE
Embedding Concatenation in forward() Function

### ISSUE THREAD

**Issue by qihan96** [Alpha-VLLM/LLaMA2-Accessory#32]
Hi! Thanks for helping out with my questions.
Why is the embedding concatenation different in forward() and forward_inference()?
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/625dae647fef5d214dde9fb8b2900923c95d8b1f/accessory/model/LLM/llama_qformerv2_peft.py#L369
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/625dae647fef5d214dde9fb8b2900923c95d8b1f/accessory/model/LLM/llama_qformerv2_peft.py#L394

**Comment by ChrisLiu6** [comment]
I think they are the same from the computation perspective. There's no special consideration here :)

**Comment by ChrisLiu6** [comment]
> Thanks for following up! How is the difference influencing the code results?

Well, the difference does not seem to be very significant.

**Comment by qihan96** [comment]
Got it. Thank you for the timely response. Appreciated.
