### ISSUE TITLE
7B Multimodal checkpoint

### ISSUE THREAD

**Issue by kai-wen-yang** [Alpha-VLLM/LLaMA2-Accessory#37]
Hi, thanks for the significant work.
Due to the lack of RAM, I can not load 13b model.
Can you please provide mutimodal 7b checkpoint such as alpacaLlava_llamaQformerv2_7b and alpacaLlava_llamaQformerv2Peft_7b.
It will help me a lot, thanks very much!

**Comment by gaopengpjlab** [comment]
We will release a 7B mulitmodal within one week. Thanks for your advice.

**Comment by kai-wen-yang** [comment]
Thx, it's very nice.

**Comment by kriskrisliu** [comment]
> Hi, thanks for the significant work. Due to the lack of RAM, I can not load 13b model. Can you please provide mutimodal 7b checkpoint such as alpacaLlava_llamaQformerv2_7b and alpacaLlava_llamaQformerv2Peft_7b. It will help me a lot, thanks very much!

As you've mentioned limited resources problem, please check [the quantization approach in our document](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/finetune.md#quantization-assisted-parameter-efficient-fine-tuning). With quantization, llamaQformerv2_13b could be loaded in a single GPU of >13GB VRAM for inference.

**Comment by kai-wen-yang** [comment]
> > Hi, thanks for the significant work. Due to the lack of RAM, I can not load 13b model. Can you please provide mutimodal 7b checkpoint such as alpacaLlava_llamaQformerv2_7b and alpacaLlava_llamaQformerv2Peft_7b. It will help me a lot, thanks very much!
> 
> As you've mentioned limited resources problem, please check [the quantization approach in our document](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/finetune.md#quantization-assisted-parameter-efficient-fine-tuning). With quantization, llamaQformerv2_13b could be loaded in a single GPU of >13GB VRAM for inference.

The resource limit is in cpu RAM.
Before quantization, it needs to first load the model into cpu with bfloat16 and load pretrained weight, which needs >~60 cpu RAM.

**Comment by gaopengpjlab** [comment]
7B checkpoint will be released in a few days.

**Comment by Enderfga** [comment]
@MiracleHH @kai-wen-yang Hey everyone! Just wanted to let you know that the 7B checkpoint is now available on our open-source repository. Happy coding!

**Comment by MiracleHH** [comment]
Great, thanks so much!
