### ISSUE TITLE
Pre-training code

### ISSUE THREAD

**Issue by Rajratnpranesh** [Alpha-VLLM/LLaMA2-Accessory#40]
Hi, I am looking for code to pre-train llama-2, I cannot find a clear instruction for it.
Please share if someone already did it.
Thank you

**Comment by ChrisLiu6** [comment]
Hi, here is the (doc for pre-training)[https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/pretrain.md]. It also refers to the exemplary pre-training scripts. Please let me know if there is still any unclear.

**Comment by Rajratnpranesh** [comment]
Thank you. I am trying to pre-train the llama-2 model, wondering this repo supports Llama2 or Llama2-hf or Llama2-chat or Llama2-chat-hf or all? pls let me know

**Comment by ChrisLiu6** [comment]
> Thank you. I am trying to pre-train the llama-2 model, wondering this repo supports Llama2 or Llama2-hf or Llama2-chat or Llama2-chat-hf or all? pls let me know

This repo supports the original official checkpoints, including llama1, llama2, and llama2-chat. Currently it does not support huggingface-style checkpoints.
