### ISSUE TITLE
script to merge the result of main_finetune.py with llama2 weights

### ISSUE THREAD

**Issue by qihan96** [Alpha-VLLM/LLaMA2-Accessory#41]
Hi, thanks for helping answer the question.
If I only saved the trainable parameters from the main_finetune.py, how should it be merged with the llama2 weights? 
If I save both the trainable and non-trainable parameter weights from the main_finetune.py file, can they directly be used in single_turn_mm.py for demo?

**Comment by kriskrisliu** [comment]
Pass both of the base weight and the trainable weight to `--pretrained_path`

**Comment by ChrisLiu6** [comment]
> If I save both the trainable and non-trainable parameter weights from the main_finetune.py file, can they directly be used in single_turn_mm.py for demo?

Yes. As long as `--only_save_trainable` is set to `False`, you can always directly use the saved checkpoints for demos.

> If I only saved the trainable parameters from the main_finetune.py, how should it be merged with the llama2 weights?

We have recently introduced a new feature wherein all demo Python files can now accept multiple directories for the `--pretrained_path` argument. The function `util.tensor_parallel.load_tensor_parallel_model_list` will probe these paths, autonomously discern the type of pre-trained checkpoints (whether "meta_ori", "consolidated", or "diff") based on the checkpoint names, and sequentially load the checkpoints from these directories. If a parameter is found in more than one checkpoint, the latter will supersede any earlier occurrences.

Alternatively, if you wish to manually merge the checkpoints, the process is also straightforward:
``` python
for key, value in new_state_dict.items():
    ori_state_dict[key] = value
```
Please be aware that, in contrast to the original llama checkpoints, our parameter names include an additional `"llma."` prefix.

**Comment by qihan96** [comment]
Gotcha. Thanks for the detailed answer. This is very helpful!
