### ISSUE TITLE
Finetuning with quant (Integer parameters are unsupported)

### ISSUE THREAD

**Issue by qkrtnskfk23** [Alpha-VLLM/LLaMA2-Accessory#42]
When i run the finetuning code with --quant for efficient training, I got an error " Integer parameters are unsupported" in torch/distributed/fsdp/flat_param.py", line 435, in _init_flat_param.

Is there any solution for this issue?

Thanks.

**Comment by kriskrisliu** [comment]
--llama_type should be "llama_peft" when using quantization. Please check the document where we show examples of how to run with quantization. https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/finetune.md#quantization-assisted-parameter-efficient-fine-tuning

See the quantization finetuning script: https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/accessory/exps/finetune/sg/alpaca_llamaPeft_normBias_QF.sh

**Comment by qkrtnskfk23** [comment]
Thank you! The problem is solved!!
