### ISSUE TITLE
trouble downloading llama2-qformer-peft-13B delta weights

### ISSUE THREAD

**Issue by qihan96** [Alpha-VLLM/LLaMA2-Accessory#44]
Hi, I ran `python3 download.py --model_name alpacaLlava_llamaQformerv2Peft_13b --input_type mm --output_path /home/path/to/save --model_size 13B --down_config`.
Then I got the error saying model.pth file not found. I think the remote file pointed by the symbolic link is no longer there.
Thanks for helping!

**Comment by Enderfga** [comment]
Hello! I have tested the following command (with default download path), and it can be downloaded successfully. Maybe you can try a few more times. I guess the failure is due to network problems.
```shell
python tools/download.py  --model_name alpacaLlava_llamaQformerv2Peft_13b --model_size 13B --input_type mm --down_config
```

**Comment by qihan96** [comment]
Okie! I will try more times then haha.
