### ISSUE TITLE
Which Pre-trained Path to Use at When

### ISSUE THREAD

**Issue by qihan96** [Alpha-VLLM/LLaMA2-Accessory#49]
Hey,

What are the pre-trained weights to use for stage 1 multi-modal training if not llama2 original weights?

My current understanding is the following:

> **inference** uses the checkpoints result from **stage 2 multi-modal finetuning** as pre-trained path
> **stage 2 multi-modal finetuningl** uses the checkpoints from **stage1 multi-modal finetuning** results

Background for this issue: I am running main_finetune.py with LLaMA2 as base weights, skipping stage 1 by training all trainable parameters at once with llava-150k-dataset (no conversion to single-turn), merging the delta weights with LLaMA2 base weights. Running the inference after the above process gives nonsense output. There probably is a lot of reasons why it fails, but I would like to check in what is the expect pretrained path first.

I did not find anything explaining the motivation of pretraining with [RefinedWeb](https://huggingface.co/datasets/tiiuae/falcon-refinedweb) and [StarCoder](https://github.com/bigcode-project/starcoder) in this github repo or the Adapter paper. It would be great if you can explain what the relationship between pre-training scripts and two stages of finetuning script.

Thanks a ton!!

**Comment by Enderfga** [comment]
Thank you for your insightful inquiry into our project. I appreciate your interest and am pleased to provide detailed responses to your questions.

1. **Pre-Trained Weights Selection**: Regarding the issue you mentioned about not using the LLaMA2 original weights in the first stage of multimodal training, I want to make sure I understand your intention. Are you referring to using the weights we released that were fine-tuned on LLaMA2? I think it's feasible to use these weights. The first stage is an essential part of the training process, but if you choose to use the first stage weights we released and then conduct the second stage training, that is also reasonable and feasible.

2. **Understanding of Training Stages**:
   - **Stage 1**: This stage involves training with image-text pairs, enabling the model to comprehend images and caption them. The model trained in this phase serves as a pre-trained base for stage 2.
   - **Stage 2**: Building upon the weights obtained from stage 1, the second stage consists of instruction tuning with image-question pairs to further enhance the model's multi-modal capabilities.

3. **Regarding the Nonsense Output Issue**: Many factors could lead to an unsuccessful inference. As the inference phase relies on weights trained in stage 2, it's imperative to ensure both stages have been executed properly. Merging the delta weights and training all trainable parameters at once might introduce complexity, and I would recommend adhering to the base training process before venturing into custom training or finetuning adjustments.

4. **On RefinedWeb and StarCoder**: As a supplementary note, RefinedWeb and StarCoder are extensive text corpora datasets, from where LLaMA would generally be trained from scratch. In traditional multi-modal training, these datasets may not be applicable.

I hope this information clarifies your inquiries. If you have any more questions or need further clarification, please don't hesitate to reach out.

**Comment by qihan96** [comment]
Hi, Sorry if the question was not clear. I understand the training script for stage 1 training is not released yet. I meant to ask what is the base weights / pretrained weights used for stage 1, and how that is different from llama2 original weights or not. Thanks for these detailed responses. I appreciate them.

**Comment by Enderfga** [comment]
The base language model for stage one is the official llama2.
