### ISSUE TITLE
about demos/single_turn_mm.py

### ISSUE THREAD

**Issue by 2201957** [Alpha-VLLM/LLaMA2-Accessory#50]
question about “torchrun --nproc-per-node=2  demos/single_turn_mm.py \
--llama_config /path/to/params.json --tokenizer_path /path/to/tokenizer.model \
--pretrained_path /path/to/multimodel_llama”

Can you please provide an example of this command? Sincerely thanks！

**Comment by Enderfga** [comment]
Here is how to use two multimodel models that we have open-sourced. The specific path depends on your saved path. If you have any questions, please feel free to ask.
```shell
torchrun --nproc-per-node=2  demos/single_turn_mm.py \
--llama_config /path/to/13B_params.json --tokenizer_path /path/to/tokenizer.model \
--pretrained_path /path/to/alpacaLlava_llamaQformerv2_13b

torchrun --nproc-per-node=2  demos/single_turn_mm.py \
--llama_config /path/to/13B_params.json configs/model/finetune/sg/llamaPeft_normBiasLora.json \
--tokenizer_path /path/to/tokenizer.model \
--pretrained_path /path/to/alpacaLlava_llamaQformerv2Peft_13b
```

**Comment by ryuji-fujieda** [comment]
Do you not need to specify llama_type in the sample below?
Do we specify llama_qformerv2?
```
torchrun --nproc-per-node=2  demos/single_turn_mm.py \
--llama_config /path/to/13B_params.json --tokenizer_path /path/to/tokenizer.model \
--pretrained_path /path/to/alpacaLlava_llamaQformerv2_13b
```
