### ISSUE TITLE
Config of Two-Stage Training of Multi-Modal LLaMA2

### ISSUE THREAD

**Issue by CaraJ7** [Alpha-VLLM/LLaMA2-Accessory#61]
Hi. I would like to train the stage2 based on your released stage1 model. I am following the instruction from https://llama2-accessory.readthedocs.io/en/latest/finetune/mm.html#stage2.

However, I could not find the corresponding config of stage2 model. Specifically, the `llama_config` defined in `accessory/exps/finetune/mm/alpacaLlava_llamaQformerv2_13B.sh`. May you kindly provide it? Thank you.

**Comment by Enderfga** [comment]
https://huggingface.co/Alpha-VLLM/LLaMA2-Accessory/blob/main/config/13B_params.json

**Comment by CaraJ7** [comment]
Thanks for your answer!
