### ISSUE TITLE
LLaMA2-Adaptor x Region Demo setting

### ISSUE THREAD

**Issue by erjui** [Alpha-VLLM/LLaMA2-Accessory#63]
Hi, first of all, thanks for the nice work.

The demo of the multi-modal llama2-adaptor and region is really nice that it even finds bounding boxes of the given image. However, when I tried the same thing on the llama2-adaptor demo page, it seemed the model did not give a proper answer. (http://llama-adapter.opengvlab.com/)

So I wonder if there is a difference when training/fine-tuning the llama2-adaptor model on multi-modal visual instructions.

Thanks in advance :)

![image (1)](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/36221725/01fa5c17-1dfc-4e6f-a627-7e971de59bc8)

**Comment by Artanic30** [comment]
Hello, thank you for your interest in our work. At the moment, the demo model does not incorporate bounding boxes, which means it cannot generate location information as requested in the prompt. However, we are actively working on the llama2-adaptor with localization capabilities, and we will eagerly share the intriguing demo with you as soon as our research is complete.

**Comment by erjui** [comment]
Thanks a lot for the answer!
However then, I'm very curious about how you incorporate bounding box localization from the prompt.
Could you tell me how you integrated such localization ability??

**Comment by gaopengpjlab** [comment]
We will release the training pipeline for incorporating box into LLM.
Stay tuned.

**Comment by erjui** [comment]
Thanks a lot for the answer! 👍

**Comment by gaopengpjlab** [comment]
Please try SPHINX which shows strong performance on object spotting.
