### ISSUE TITLE
webbook documentation 错误百出

### ISSUE THREAD

**Issue by HLearning** [Alpha-VLLM/LLaMA2-Accessory#64]
文档更新不及时， 命令错误百出， 看了文档多花了半天时间调试代码。。。

**Comment by Enderfga** [comment]
您好，

首先，我非常抱歉给您带来了不便。感谢您的反馈，这对于我们持续改进项目非常有价值。我承认文档的更新和维护是一个持续的过程，有时可能出现延迟或遗漏。我会尽快修复文档中的错误，并尝试使其更为及时和准确。

您目前提到的更新不及时以及错误是指哪部分内容呢？请随时与我分享。
