### ISSUE TITLE
Error : NotImplementedError: offload_to_cpu=True and NO_SHARD is not supported yet

### ISSUE THREAD

**Issue by WeiXuanLi-1024** [Alpha-VLLM/LLaMA2-Accessory#76]
我使用  alpacaLlava_llamaQformerv2Peft_QF_13B.sh  微调模型，在迭代完一次epoch ，
保存模型时出现了错误，使用单卡跑的。脚本内容如下
![2ae814302c794ac8582b4991947af66](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/24350444/faac3cbb-9e97-4cd3-9b09-68d1f7e02585)

` File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 171, in _unshard_fsdp_state_params
    _validate_unshard_params_args(
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 140, in _validate_unshard_params_args
    raise NotImplementedError(
NotImplementedError: offload_to_cpu=True and NO_SHARD is not supported yet
`

**Comment by kriskrisliu** [comment]
The script is correct.
Please show us the complete error logs.

**Comment by WeiXuanLi-1024** [comment]
![3ff401903d494fa95c3b349dee605c6](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/24350444/4379e079-132b-420b-881b-f11c92db60bc)

**Comment by kriskrisliu** [comment]
Did you modify any codes?

**Comment by WeiXuanLi-1024** [comment]
使用的单GPU

**Comment by WeiXuanLi-1024** [comment]
这个问题已经解决：参考https://github.com/huggingface/accelerate/pull/1745/commits/940ae8dfff504ce7e7e3015bcbbd17e3e8cd3157

原因： # FSDP raises error when single GPU is used with `offload_to_cpu=True` for FULL_STATE_DICT
            # so, only enable it when num_processes>1
           也就是在使用单GPU时，必须要将本仓库中 misc.py line348  两个参数设置为  rank0_only=False, offload_to_cpu=False

设置完运行结果：正常保存
![336d5fb3faa7083c8645a8d8002f0bd](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/24350444/9c374da3-2a09-495e-8fc1-3ba78fabd144)

**Comment by funkyyyyyy** [comment]
> 这个问题已经解决：参考[huggingface/accelerate@940ae8d](https://github.com/huggingface/accelerate/commit/940ae8dfff504ce7e7e3015bcbbd17e3e8cd3157)
> 
> 原因： # FSDP raises error when single GPU is used with `offload_to_cpu=True` for FULL_STATE_DICT # so, only enable it when num_processes>1 也就是在使用单GPU时，必须要将本仓库中 misc.py line348 两个参数设置为 rank0_only=False, offload_to_cpu=False
> 
> 设置完运行结果：正常保存 ![336d5fb3faa7083c8645a8d8002f0bd](https://user-images.githubusercontent.com/24350444/270517804-9c374da3-2a09-495e-8fc1-3ba78fabd144.png)
