### ISSUE TITLE
InternLM inference and training are problematic

### ISSUE THREAD

**Issue by June01** [Alpha-VLLM/LLaMA2-Accessory#78]
The following is my code to run the demo, with [pretrained model](https://huggingface.co/Alpha-VLLM/LLaMA2-Accessory/blob/main/finetune/sg/alpaca_internLM_zh/consolidated.00-of-01.model.pth), [llama_config](https://huggingface.co/Alpha-VLLM/LLaMA2-Accessory/blob/main/config/internLM_7B_params.json), [tokenizer](https://huggingface.co/Alpha-VLLM/LLaMA2-Accessory/blob/main/config/internLM_tokenizer.model). However, the output of the network is chaos even with a simple Question "hello". Could you please look into it?

``` 
torchrun --nproc-per-node=1  demos/single_turn.py \
--llama_config /path/to/params.json --tokenizer_path /path/to/tokenizer.model \
--pretrained_path /path/to/alpaca_finetuned
```

![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/12269592/7459e1dc-38f8-4930-9bec-c7da4f1e878a)

**Comment by ChrisLiu6** [comment]
You are now loading internlm checkpoint to a llama model, Please try adding `--llama_type internlm`.

**Comment by June01** [comment]
Thanks! It works.
