### ISSUE TITLE
Warning instead of Error

### ISSUE THREAD

**Issue by yeonju7kim** [Alpha-VLLM/LLaMA2-Accessory#83]
Hello. I'm currently using this repo a lot. Thank you for your good work.

https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/a76a29070a718e1aad4d4e493503d278b29d5c6a/accessory/configs/global_configs.py#L6C1-L6C28

I think the above should be just except instead of except ModuleNotFoundError

**Comment by ChrisLiu6** [comment]
You are right, thank you! `ModuleNotFoundError` is now changed to the general `ImportError`, see https://github.com/Alpha-VLLM/LLaMA2-Accessory/commit/448bcaf3695c955e0de9079a1606f2c605ae16cf
