### ISSUE TITLE
Failed to convert to HF

### ISSUE THREAD

**Issue by arbindpd96** [Alpha-VLLM/LLaMA2-Accessory#84]
I am trying to convert a fine tuned checkpoint to hf so i can make the model work with llama.cpp
Image attached for reference
Any help would be appreciated.

Also in the latest commit 
> in accessory/main_finetune.py FuseAdam is imported as AdamW but used as FuseAdam. which causes it to break.
>  also we are getting a key error on the key 'image' on this line
print(f'Warning for truncation input!\nImage name: {data_item["image"]} question: {data_item["question"][:10]}')
in accessory/data/alpaca.py

![image](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/20431615/d79f1f92-ef0f-41b8-975a-701cc07edb58)

**Comment by anuragdalia** [comment]
Hey thanks for that response.

Can these checkpoints be used with llama.cpp or as a quantized single bin file. or even be converted to ggml format? 
or all these would require custom scripts ?

**Comment by anuragdalia** [comment]
@ChrisLiu6 
Hi 
Please suggest.

**Comment by ChrisLiu6** [comment]
I'm sorry, but I'm really not familiar with llama.cpp😣. Unfortunately, no one on our team is working on that. The followings are all I can provide on this topic:

+ The `convert_weights_to_hf` script is designed exclusively for the original llama architecture. Therefore, you may fully finetune your model using Accessory and then convert it to Hugging Face. You can refer to [this experiment](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/accessory/exps/finetune/sg/alpaca.sh).
+ If you do require PEFT, consider finetuning only the norm and Lora. Afterward, merge the Lora weights into the original weights before the conversion to Hugging Face. This will make a checkpoint compatible with the original llama architecture. However, you'll need to implement the Lora merging logic on your own.
+ If you do need to keep the bias terms in the model and convert it to HF, you may need to modify the HF llama implementation to make it contain the bias terms. You also need to modify the `convert_weights_to_hf` script to deal with biases.
