### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by yeonju7kim** [Alpha-VLLM/LLaMA2-Accessory#86]
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/a0b87081e8476e2a857302c202ec7bf51fd3f38f/accessory/data/alpaca.py#L118

I thought that this should be 
```python
labels[:len(input1) - 1] = -1
```

**Comment by ChrisLiu6** [comment]
I guess you are considering that the output of the token with index [len(input1) - 1] should already be taken into account for loss calculation. This is true, but please consider here:

https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/a0b87081e8476e2a857302c202ec7bf51fd3f38f/accessory/model/meta.py#L86

The central point here is that the label should be one token ahead of input.

**Comment by yeonju7kim** [comment]
When I debugged this part, I found that the label doesn't contain one starting token of ground truth. 
For example, if the ground truth is "This is a cat", the label is " is a cat".
