### ISSUE TITLE
How can we transform the hugging format weight into the meta format? 

### ISSUE THREAD

**Issue by ZhenYangIACAS** [Alpha-VLLM/LLaMA2-Accessory#87]
Hi, 
Thanks for your great work! My issue is:
I have downloaded the hugging format weight of llama2, which like this: pytorch_model-00001-of-00002.bin
how can it be loaded by your code or do you have scripts to convert it to the supported format?
Thanks a lot.

**Comment by ChrisLiu6** [comment]
Well, theoretically, HF checkpoints and Meta checkpoints are interchangeable. However, while a conversion script from Meta to HF is available in HF's repository, I'm not sure if a public implementation exists for the reverse conversion. Please verify this yourself.
