### ISSUE TITLE
Multimodal finetunning code? 

### ISSUE THREAD

**Issue by waybarrios** [Alpha-VLLM/LLaMA2-Accessory#9]
Is there any example?

**Comment by gaopengpjlab** [comment]
Multimodal finetunning code will be released within one week.

**Comment by yuntaodu** [comment]
> Multimodal finetunning code will be released within one week.

Looking forward to this!

**Comment by YmanChris** [comment]
> > Multimodal finetunning code will be released within one week.
> 
> Looking forward to this!

+1

**Comment by ChrisLiu6** [comment]
Hi all, you can find the multi-modal fine-tuning scripts [here](https://github.com/Alpha-VLLM/LLaMA2-Accessory/tree/main/accessory/exps/finetune/mm). Pretrianed checkpoints and documents will be released soon.

**Comment by waybarrios** [comment]
nice! appreciate it. Thank you @ChrisLiu6

**Comment by waybarrios** [comment]
I think this issue should be marked as done.
