### ISSUE TITLE
full parameter finetuning on A100 40G

### ISSUE THREAD

**Issue by ZhenYangIACAS** [Alpha-VLLM/LLaMA2-Accessory#91]
Hi,  can the code of the current version be full-parameter finetuning on A100 40G ? I have tried, but find the GPU memory only supports 10 layers finetuning. If ok, can you show me the right setting?

**Comment by ChrisLiu6** [comment]
How many GPUs do you have? More GPUs will reduce the burden on each individual. Furthermore, the model size and the sequence length are all influential to the conclusion.

**Comment by ZhenYangIACAS** [comment]
8 GPUs, max_words = 512, 7B

**Comment by ChrisLiu6** [comment]
That should be enough. You may try the following practices if you meet OOM problem:
1. reduce the batch size
2. turn on graidient checkpointing (add `--checkpointing` to the `main_fiunetune.py` starting command)
3. change data parallel strategy from sdp to fsdp
