### ISSUE TITLE
cant find the sphinx model from huggingface

### ISSUE THREAD

**Issue by yjhdhr** [Alpha-VLLM/LLaMA2-Accessory#94]
I notice that you would release a new version. 
May I ask when we can use the latest model?
THX～

**Comment by ChrisLiu6** [comment]
Thank you for your interest in our work! This time we will release the checkpoints for two different models including the powerful Long-SPHINX model (MME 1560). The checkpoints are being uploaded right now, but the transfer speed seems to be really unstable. We conservatively estimate the whole process will be done within the next 24 hours.

**Comment by gaopengpjlab** [comment]
https://huggingface.co/Alpha-VLLM/LLaMA2-Accessory/tree/main/finetune/mm/SPHINX

**Comment by yjhdhr** [comment]
Thanks ~~Get it!
