### ISSUE TITLE
Citation information for SPHINX

### ISSUE THREAD

**Issue by taesiri** [Alpha-VLLM/LLaMA2-Accessory#96]
Hello and first of thank you for your amazing work.

We would like to cite your recent model SPHINX, but we are unsure of which citation we should use for it. Could you please provide a BibTeX for this?

Thanks a lot.

**Comment by gaopengpjlab** [comment]
Paper will be uploaded to arxiv soon. We will notice you by then. Thanks for you interest in SPHINX.

**Comment by gaopengpjlab** [comment]
https://arxiv.org/pdf/2311.07575.pdf paper is shown on arxiv.

**Comment by taesiri** [comment]
This is awesome, thank you so much. I will close this issue.
