### ISSUE TITLE
Can SPHINX be fine-tuned?

### ISSUE THREAD

**Issue by xulinui** [Alpha-VLLM/LLaMA2-Accessory#98]

**Comment by gaopengpjlab** [comment]
<img width="729" alt="Screen Shot 2023-11-11 at 10 47 23" src="https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/105254043/e496884a-4498-4e85-ae5a-6cd989bbb487">

**Comment by gaopengpjlab** [comment]
Finetuning from released SPHINX checkpoint should be quite easy and stable. A finetuning tutorial will be released soon.
